### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by sean-hill** [starters/kik#4]
$ npm install -g kik
    kik@1.0.2 /usr/local/lib/node_modules/kik
    $ kik
    -bash: kik: command not found

**Comment by azer** [comment]
npm install -g azer/kik

**Comment by sean-hill** [comment]
@azer 
	$ npm install -g azer/kik
	npm ERR! Darwin 15.3.0
	npm ERR! argv "/usr/local/Cellar/node/4.2.1/bin/node" "/usr/local/bin/npm" "install" "-g" "azer/kik"
	npm ERR! node v4.2.1
	npm ERR! npm  v2.14.7
	npm ERR! code ETARGET

	npm ERR! notarget No compatible version found: cli-form@'>=0.1.2 <0.2.0'
	npm ERR! notarget Valid install targets:
	npm ERR! notarget ["2.0.0","0.0.1-security"]
	npm ERR! notarget
	npm ERR! notarget This is most likely not a problem with npm itself.
	npm ERR! notarget In most cases you or one of your dependencies are requesting
	npm ERR! notarget a package version that doesn't exist.
	npm ERR! notarget
	npm ERR! notarget It was specified as a dependency of 'kik'
	npm ERR! notarget

	npm ERR! Please include the following file with any support request:
	npm ERR!     /Users/Comfy-Blitz/Desktop/npm-debug.log

**Comment by azer** [comment]
oh yeah, all dependencies are broken. I gotta fix it when i work on it again

**Comment by sean-hill** [comment]
Cool :smile: No rush!
