### ISSUE TITLE
Kik on The Changelog!

### ISSUE THREAD

**Issue by adamstac** [starters/kik#8]
Howdy from The Changelog!

Wow, what a ride! How would you like to come on the show and get some focus on your project vs all the other talk about npm and all that? Sure, we can mention that too, but why not promote your project and share on our show how folks can continue to use and support kik.

If you haven't heard of the show, The Changelog is a podcast published weekly on Friday that covers what's fresh and new in open source. You can listen to the show here https://changelog.com/podcast

Looking forward to talking to you.

Adam, EIC

**Comment by azer** [comment]
@adamstac hi adam! I really appreciate the offer but it'd be inappropriate for me to promote Kik in this situation. I'd love to move on from NPM situation in general. 

Cheers 

Azer

**Comment by adamstac** [comment]
We're not inviting you to come on the show to talk about kik because of this situation, but it's because of this that your project caught our attention.

Lots of people on our email list want to hear more about your project too.

We're not open for 4 weeks anyways. Are you sure you want to pass?

**Comment by azer** [comment]
@adamstac yeah, sooner I move on from this stuff is better for me. thank you
